[window]

decorations = "Full"
decorations_theme_variant = "Dark"

[font]
#normal = { family = "Hurmit Nerd Font", style = "Regular" }
#bold = { family = "Hurmit Nerd Font", style = "Bold" }
#italic = { family = "Hurmit Nerd Font", style = "Italic" }
#bold_italic = { family = "Hurmit Nerd Font", style = "Bold Italic" }

normal = { family = "UbuntuMono Nerd Font", style = "Regular" }
bold = { family = "UbuntuMono Nerd Font", style = "Bold" }
italic = { family = "UbuntuMono Nerd Font", style = "Italic" }
bold_italic = { family = "UbuntuMono Nerd Font", style = "Bold Italic" }
size = 14

[cursor]
style = { shape = "Block", blinking = "On" } 

[mouse]
hide_when_typing = true

